set(_CATKIN_CURRENT_PACKAGE "decision")
set(decision_VERSION "0.1.0")
set(decision_MAINTAINER "Sébastien Darche <sebastien.darche@polymtl.ca>")
set(decision_PACKAGE_FORMAT "2")
set(decision_BUILD_DEPENDS "detection" "serial" "tracking")
set(decision_BUILD_EXPORT_DEPENDS )
set(decision_BUILDTOOL_DEPENDS "catkin")
set(decision_BUILDTOOL_EXPORT_DEPENDS )
set(decision_EXEC_DEPENDS "detection" "serial" "tracking")
set(decision_RUN_DEPENDS "detection" "serial" "tracking")
set(decision_TEST_DEPENDS )
set(decision_DOC_DEPENDS )
set(decision_URL_WEBSITE "")
set(decision_URL_BUGTRACKER "")
set(decision_URL_REPOSITORY "")
set(decision_DEPRECATED "")